spring.application.name=BonusServer

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bonus_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:bonus_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bonus_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.security.read.username=${APP_SECURITY_READ_USERNAME:reader}
app.security.read.password=${APP_SECURITY_READ_PASSWORD:reader123}
app.security.write.username=${APP_SECURITY_WRITE_USERNAME:writer}
app.security.write.password=${APP_SECURITY_WRITE_PASSWORD:writer123}

server.port=${SERVER_PORT:8080}
