spring.application.name=BonusServer

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bonus_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:bonus_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bonus_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


server.port=${SERVER_PORT:8080}
